main = ".open-next/worker.js"
name = "ai-service"
compatibility_date = "2025-09-13"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public",]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "ai-service-prod"
database_id = "777fda96-9f17-4487-b0a2-38629ebc865a"
migrations_dir = "./drizzle"